// generalReducer.js
import {createSlice} from '@reduxjs/toolkit';

const initialState = {
  online: false,
  refetch: 0,
  offlineData: [],
};

const generalReducer = createSlice({
  name: 'counter', // Name of the slice
  initialState, // Initial state of the counter
  reducers: {
    // Reducer functions here
    setIsOnline: (state, action) => {
      state.online = action.payload;
    },
    setOfflineData: (state, action) => {
      state.offlineData = action.payload;
    },
    setRefetch: (state, action) => {
      state.refetch = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const {setIsOnline, setOfflineData, setRefetch} = generalReducer.actions;

// Export the reducer itself
export default generalReducer.reducer;
