// userReducer.js
import {createSlice} from '@reduxjs/toolkit';

const initialState = {
  userData: null,
  token: null,
};

const userReducer = createSlice({
  name: 'user', // Name of the slice
  initialState, // Initial state of the user
  reducers: {
    // Reducer functions here
    setUserData: (state, action) => {
      state.userData = action.payload;
    },
    setToken: (state, action) => {
      state.token = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const {setUserData, setToken} = userReducer.actions;

// Export the reducer itself
export default userReducer.reducer;
